### PR TITLE
Supports if clause in comprehension with sum/prod.

### PR DESCRIPTION
**Pull request by odashi**
# Overview

Supports following expression:

# Details

Converts the `ifs` subtrees into expression and joins all conditions with `\land` ( $\land$ ).

# References

NA

# Blocked by

- #77

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
The code looks good to me. But I have a few questions on this notation:

> joins all conditions with \land

Do you have any references to justify that the notation is common? I couldn't find the usage of \land in https://en.wikipedia.org/wiki/Summation 

And I think braces e.g. $(i \in n) \land (i < 3)$ would make subscripts more readable and robust against operator precedence.

**Review by ShigekiKarita — APPROVED** [review]

**Comment by odashi** [comment]
@ShigekiKarita
This would be the corresponding explanation (in Wikipedia):



> And I think braces e.g. (...formulas...) would make subscripts more readable

Yeah I also think so, let me fix it.

**Comment by odashi** [comment]
Now the output looks:

**Comment by ShigekiKarita** [comment]
Fair enough. Thanks!

**Review by ShigekiKarita — APPROVED** [review]
LGTM again.

**Pull request merged**
