### PR TITLE
publish algorithmic decorator

### PR DESCRIPTION
**Pull request by odashi**
# Overview

Publish `latexify.algorithmic`.

# References

- #57

# Blocked by

NA

### CODE REVIEW

**Review by ZibingZhang — APPROVED** [review]

**Review by ShigekiKarita — APPROVED** [review]

**Comment by luisArandas** [comment]
Amazing to see this going. I still see no examples on the notebook. What is the way you recommend to generate algorithmic environments? Can I access `latexify.algorithmic` on the current pip version somehow?

**Comment by odashi** [comment]
@luisArandas It is still under development. If you want to try it out, you need to checkout this repository directly and install it manually. We will include this feature in the next release (v0.3).

**Comment by luisArandas** [comment]
Ok amazing, when is it coming out, do we you have a date? Thanks for this

**Comment by luisArandas** [comment]
Using the current state of the library I can render the algorithmic view table 👍 but some features are not working like for loops, will wait for your work on this

**Comment by ZibingZhang** [comment]
@luisArandas any other features you're looking for besides for loops?

**Comment by odashi** [comment]
I'm currently not available to develop new features due to increasing work load of the main work. I'd appreciate it if @ZibingZhang and @luisArandas discuss about missing features (I can process reviewing though)

**Comment by luisArandas** [comment]
That is a great question! We can discuss this with more time. I would say for loops, whiles and just function logic for now (which might already work easily, embed functions there)

**Comment by odashi** [comment]
Since this issue has been closed, it would be great if we open another issue ;)

**Pull request merged**
